sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    username: root
    password: '031024'
    database: sky
  redis:
    host: 192.168.100.128
    port: 6379
    password: ''
  nacos:
    server-addr: 192.168.100.128:8848